name: Push to main

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    # Note: The below workflow is a copy of the one in the oodlefinance/github-actions repo.
    # This is due to common-build being a public repository (needed for external access of the build files)
    # and github-actions being a private one - see https://docs.github.com/en/actions/sharing-automations/reusing-workflows#access-to-reusable-workflows
    uses: ./.github/workflows/create-timestamp-tag.yaml
